version: '3'
services:
   passwordgenerator:
      build:
          context: .
          dockerfile: Dockerfile
      image: infotekies/password-generator-service:latest
      container_name: passwordgenerator
      stdin_open: true
      tty: true
      ports:
         - 8080:8080
