#!/bin/bash
script_dir=`dirname $(readlink  $0)`
cd ${script_dir}
count=`ls -1 ./target/PasswordGenerator-*.jar 2> /dev/null  | wc -l | tr -d ' '`
if [ "${count}" == "0" ]
then
	mvn package
fi
java -cp "./src/main/resources:./target/*"  com.infotekies.passwdgen.PasswordGenerator
