#!/bin/bash
fn=`readlink $0`
if [ "${fn}x" = "x" ]
then
	fn=${0}
fi
script_dir=`dirname ${fn}`
cd ${script_dir}
if [ -d ./target ]
then
	count=`ls -1 ./target/PasswordGenerator-*.jar 2> /dev/null  | wc -l | tr -d ' '`
	if [ "${count}" == "0" ]
	then
		mvn package
	fi
fi

PID_FILE="${HOME}/.passwordgen.pid"
LOG_FILE=passwdgen-nohup-out.log

nohup java -cp "./config:./lib/*:./src/main/resources:./target/*" \
		-Dloader.main=com.infotekies.passwdgen.SpringBootMainApp \
		org.springframework.boot.loader.PropertiesLauncher $* > ${LOG_FILE} 2>&1

PID=$!

echo "${PID}" > ${PID_FILE}

#
# To stop the container from Exiting, do tail of /dev/null
#

tail -f /dev/null

