#!/bin/bash
fn=`readlink $0`
if [ "${fn}x" = "x" ]
then
	fn=${0}
fi
script_dir=`dirname ${fn}`
cd ${script_dir}/..
count=`ls -1 ./target/PasswordGenerator-*.jar 2> /dev/null  | wc -l | tr -d ' '`
if [ "${count}" == "0" ]
then
	mvn package
fi
java -cp "./src/main/resources:./target/*"  \
		-Dspring.main.banner-mode=off   \
		-Dlogging.level.root=error    \
		-Dspring.main.web-application-type=none \
		-Dloader.main=com.infotekies.passwdgen.PasswordGenerator org.springframework.boot.loader.PropertiesLauncher $*
